version: 2.1
jobs:
        build:
                docker:
                        - image: cirlceci/node:4.8.2
                steps:
                        - checkout
                        - run: echo "Hello, World!"
